spring:
  profiles:
    include:
      - comm
---
server:
  config:
    activate:
      on-profile: prod
  port: 8080
  error.include-message: always
  tomcat:
    max-swallow-size: -1
  host:
    adminApi: https://profile-box-api-admin.default.svc.cluster.local:8080
---
server:
  servlet:
    context-path: /

logging:
  level:
    root: DEBUG

api:
  common:
    version: 1.0.0
    title: Profile Box User API
    description: Profile Box User API
    termsOfServiceUrl:
    license: License
    licenseUrl: MY LICENSE URL
    contact:
      name: Contact
      url: My
      email: me@mail.com

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

---
server:
  config:
    activate:
      on-profile: local
  port: 7001
  error.include-message: always
  tomcat:
    max-swallow-size: -1
  host:
    adminApi: http://localhost:7002

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/profile_box
    username: admin
    password: admin
  data:
    redis:
      host: localhost
      port: 6379
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: myGroup
